FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM python:3.9-alpine
RUN pip install http.server
COPY --from=build /app/build /app
WORKDIR /app
EXPOSE 8000
CMD ["python", "-m", "http.server", "8000"]
